[loggers]
keys=root, gameLogger, userLogger, commandLogger

[handlers]
keys=rootHandler, gameHandler, userHandler, commandHandler

[formatters]
keys=commonFormat

[logger_root]
level=WARNING
handlers=rootHandler


[logger_gameLogger]
level=DEBUG
handlers=gameHandler
qualname=gameLogger
propagate=0

[logger_userLogger]
level=INFO
handlers=userHandler
qualname=userLogger
propagate=0

[logger_commandLogger]
level=INFO
handlers=commandHandler
qualname=commandLogger
propagate=0

[handler_rootHandler]
class=FileHandler
level=INFO
formatter=commonFormat
args=('logging/main.log',)

[handler_gameHandler]
class=FileHandler
level=DEBUG
formatter=commonFormat
args=('logging/gameLog.log',)

[handler_userHandler]
class=FileHandler
level=INFO
formatter=commonFormat
args=('logging/userLog.log',)

[handler_commandHandler]
class=FileHandler
level=INFO
formatter=commonFormat
args=('logging/commandLog.log',)


[formatter_commonFormat]
format=%(asctime)s-%(name)s-%(levelname)s-%(message)s